# Generated by Django 3.2 on 2021-08-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('url', models.URLField(blank=True)),
                ('start_price', models.IntegerField()),
                ('category', models.CharField(choices=[('FAS', 'Fashion'), ('TOY', 'Toy & Hobbies'), ('ELE', 'Electronics'), ('HOM', 'Home & Garden'), ('MUS', 'Music'), ('MOV', 'Movies'), ('BOO', 'Books'), ('COL', 'Collectibles & Art'), ('SPO', 'Sporting Goods'), ('BUS', 'Business & Industrial'), ('HEA', 'Health & Beauty'), ('AUT', 'Auto & Motors'), ('OTH', 'Others')], max_length=3)),
                ('lister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.CharField(max_length=2000)),
                ('comment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commenting', to=settings.AUTH_USER_MODEL)),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_price', models.IntegerField()),
                ('bid_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidding', to='auctions.listing')),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bidded', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
