# Generated by Django 3.2 on 2021-08-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='max_bid_price',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='bid',
            name='bid_item',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_item',
            field=models.ManyToManyField(blank=True, related_name='bidding', to='auctions.Listing'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_item',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_item',
            field=models.ManyToManyField(blank=True, related_name='commenting', to='auctions.Listing'),
        ),
    ]
