# Generated by Django 3.2 on 2021-08-18 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210818_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='max_bidder',
        ),
    ]
