# Generated by Django 3.2 on 2021-08-19 00:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210818_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
