# Generated by Django 3.2 on 2021-08-19 01:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_listing_watched_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='watched_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='watching', to=settings.AUTH_USER_MODEL),
        ),
    ]
