# Generated by Django 3.2 on 2021-08-30 03:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210830_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='followings',
            field=models.ManyToManyField(blank=True, null=True, related_name='_network_user_followings_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
