# Generated by Django 3.2 on 2021-08-30 11:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20210830_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_editted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 11, 31, 3, 298798, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 11, 31, 3, 298785, tzinfo=utc)),
        ),
    ]
