# Generated by Django 3.2 on 2021-08-30 11:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_auto_20210830_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='last_editted',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 11, 45, 7, 763440, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 30, 11, 45, 7, 763440, tzinfo=utc)),
        ),
    ]
