# Generated by Django 3.2 on 2021-09-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_post_liked_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_text',
            new_name='text',
        ),
    ]
