# Generated by Django 3.2 on 2021-09-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_img',
            field=models.ImageField(blank=True, default='profile_img/default1.jpg', null=True, upload_to='profile_img'),
        ),
    ]
