# Generated by Django 3.2 on 2021-09-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_customuser_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageincomment',
            name='image',
            field=models.ImageField(upload_to='comment_img/'),
        ),
        migrations.AlterField(
            model_name='imageinpost',
            name='image',
            field=models.ImageField(upload_to='post_img/'),
        ),
    ]
