# Generated by Django 3.2 on 2021-09-23 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210923_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageincomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_image', to='network.comment'),
        ),
    ]
